---
#descriptive name of this run 
name: "default"

# which analyzer to use
analyzer: "ana_1"

shots: 100000 #total shots to simulate, this gets ignored when scan is defined

atom : #atomic system properties
 primary_binding_energy : 300.0 # in eV
 primary_hits : 10 # per shot
 primary_full_angle : 10.0 # in deg, full angle integration of primary electron 
 auger_energy : 250.0 # in eV
 auger_decay_time : 7.0 # in fs
 auger_energy_width : 0.25 # in eV
 auger_hits : 1 # per shot
 auger_full_angle: 2.0 # in deg,full angle integration of primary electron  

xfel_pulse : #XFEL pulse properties
 central_photon_energy : 425.0 # eV
 photon_energy_bandwidth : .4 # eV
 main_pulse_duration : 5.0 # fs
 plateau_duration : 200.0 # fs
 plateau_ratio : .001 #

ir_pulse : #infrared pulse properties
 wavelength : 17 # in microns
 duration : 200 # in fs
 up : 1.00 # peak Up in eV
 up_variance : .1 # eV, amount of up variance based in spatial mode properties

scan : #scan parameters, (comment it out if you don't want to scan)
 delay_start : -100.0 # fs
 delay_end : 100.0 # fs
 delay_step : 1.0 # fs
 shots_per_step : 100 #

jitter : #shot-to-shot jitter 
 timing : 100 # xfel/ir timing jitter
 ir_up : 0.0001 # UP jitter of ir pulse
 photon_energy : 4.0 #amplitude of shot to shot photon energy jitter

data :
 auger_min : 150
 auger_max : 350
 auger_bins : 400
 primary_min : 50
 primary_max : 250
 primary_bins : 400
 streak_min : -10
 streak_max : 10
 streak_bins : 200






